### ISSUE TITLE
1.19.* vewsion suppowt

### ISSUE THREAD

**Issue by ahdplayer** [Ran-Mewo/UwU#1]
can u pwease make a 1.19.2 buiwd pwease it wouwd be gweat

**Comment by Ran-Mewo** [comment]
I actually made a 1.19.2 version except the moment I was going to release it mojang decided to release 1.19.3
*breaking all my 1.19.2 code since apparently they changed their entire chat signing system in a single system*

It shouldn't be much of a hassle as I already have the code so I'll release it soon

**Comment by ahdplayer** [comment]
Thank you :)

**Comment by Ran-Mewo** [comment]
I completely forgot about this
I'll have the issue reopened so it's in my todo list and I can work on it

**Comment by OverlordGoose** [comment]
Have you finished it since then? I would love to see it in 1.19.2!

**Comment by Ran-Mewo** [comment]
Done (sorry for taking so long ehe~) https://modrinth.com/mod/uwuifier/version/TXZYuDMs
